language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master

deploy:
  # Deploy documentation
  - provider: script
    script: cargo doc && mv target/doc docs && git add -fq docs && git commit -m 'Add documentation' && git push -fq https://${GH_APIKEY}@github.com/${TRAVIS_REPO_SLUG}.git master
    on:
      branch: master
