sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master

deploy:
  # Deploy documentation
  - provider: script
    script: |
      cargo doc && sudo pip install ghp-import && ghp-import -n target/doc &&
      git push -fq https://${GH_APIKEY}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    on:
      branch: master
